[nitpick.meta]
name = "Django Flake8"
url = "https://github.com/PyCQA/flake8"

[nitpick.files.present]
".flake8" = "Create the file with the contents below"

[nitpick.files.comma_separated_values]
".flake8" = [
    "flake8.ignore",
    "flake8.extend-ignore",
    "flake8.exclude",
    "flake8.per-file-ignores",
]



[".flake8".flake8.per-file-ignores]
# Allow `__init__.py` with logic for configuration:
"**/settings/*.py" = """\
    WPS226,\
    WPS407,\
    WPS412,\
    WPS432\
"""
# Allow to have magic numbers inside migrations and wrong module names:
"**/migrations/*.py" = """\
    WPS102,\
    WPS114,\
    WPS432\
"""
