[nitpick.meta]
name = "pylint"
url = "https://github.com/pylint-dev/pylint"

[nitpick.files.present]
".pylintrc.toml" = "Create the file with the contents below"



[".pylintrc.toml".tool.pylint.design]
max-parents = 9  # Maximum number of parents for a class (see R0901).

[".pylintrc.toml".tool.pylint."messages control"]
disable = [
    "E1136",  # unsubscriptable-object

    # Disable everything that have been implemented by ruff
    # following this issue https://github.com/astral-sh/ruff/issues/970
    "E0237",  # assigning-non-slot
    "E1142",  # await-outside-async
    "E0014",  # bad-configuration-section
    "E1300",  # bad-format-character
    "E0013",  # bad-plugin-value
    "E1310",  # bad-str-strip-call
    "E1307",  # bad-string-format-type
    "E2502",  # bidirectional-unicode
    "E6005",  # broken-collections-callable
    "E6004",  # broken-noreturn
    "E0116",  # continue-in-finally
    "E0108",  # duplicate-argument-name
    "E0241",  # duplicate-bases
    "E1303",  # format-needs-mapping
    "E0102",  # function-redefined
    "E0100",  # init-is-generator
    "E0605",  # invalid-all-format
    "E0604",  # invalid-all-object
    "E0304",  # invalid-bool-returned
    "E0308",  # invalid-bytes-returned
    "E2510",  # invalid-character-backspace
    "E2513",  # invalid-character-esc
    "E2514",  # invalid-character-nul
    "E2512",  # invalid-character-sub
    "E2515",  # invalid-character-zero-width-space
    "E0309",  # invalid-hash-returned
    "E0305",  # invalid-index-returned
    "E0303",  # invalid-length-returned
    "E1206",  # logging-too-few-args
    "E1205",  # logging-too-many-args
    "E0704",  # misplaced-bare-raise
    "E1304",  # missing-format-string-key
    "E1302",  # mixed-format-string
    "E4703",  # modified-iterating-set
    "E0213",  # no-self-argument
    "E0107",  # nonexistent-operator
    "E0115",  # nonlocal-and-global
    "E0117",  # nonlocal-without-binding
    "E0103",  # not-in-loop
    "E0711",  # notimplemented-raised
    "E0643",  # potential-index-error
    "E0402",  # relative-beyond-top-level
    "E1132",  # repeated-keyword
    "E0106",  # return-arg-in-generator
    "E0101",  # return-in-init
    "E0104",  # return-outside-function
    "E1519",  # singledispatch-method
    "E1520",  # singledispatchmethod-function
    "E0001",  # syntax-error
    "E1306",  # too-few-format-args
    "E1305",  # too-many-format-args
    "E0112",  # too-many-star-expressions
    "E1301",  # truncated-format-string
    "E0603",  # undefined-all-variable
    "E0602",  # undefined-variable
    "E0302",  # unexpected-special-method-signature
    "E0601",  # used-before-assignment
    "E0118",  # used-prior-global-declaration
    "E1700",  # yield-inside-async-function
    "E0105",  # yield-outside-function
    "W1401",  # anomalous-backslash-in-string
    "W0129",  # assert-on-string-literal
    "W0199",  # assert-on-tuple
    "W3201",  # bad-dunder-name
    "W1302",  # bad-format-string
    "W0311",  # bad-indentation
    "W1501",  # bad-open-mode
    "W0211",  # bad-staticmethod-argument
    "W0702",  # bare-except
    "W0711",  # binary-op-exception
    "W1502",  # boolean-datetime
    "W0718",  # broad-exception-caught
    "W0719",  # broad-exception-raised
    "W0640",  # cell-var-from-loop
    "W0160",  # consider-ternary-expression
    "W0102",  # dangerous-default-value
    "W0705",  # duplicate-except
    "W0109",  # duplicate-key
    "W0130",  # duplicate-value
    "W1641",  # eq-without-hash
    "W0123",  # eval-used
    "W0122",  # exec-used
    "W0106",  # expression-not-assigned
    "W1309",  # f-string-without-interpolation
    "W0511",  # fixme
    "W1515",  # forgotten-debug-statement
    "W1305",  # format-combined-specification
    "W1310",  # format-string-without-interpolation
    "W0604",  # global-at-module-level
    "W0603",  # global-statement
    "W0602",  # global-variable-not-assigned
    "W1404",  # implicit-str-concat
    "W0406",  # import-self
    "W1405",  # inconsistent-quotes
    "W1508",  # invalid-envvar-default
    "W1113",  # keyword-arg-before-vararg
    "W1202",  # logging-format-interpolation
    "W1203",  # logging-fstring-interpolation
    "W1201",  # logging-not-lazy
    "W0150",  # lost-exception
    "W1518",  # method-cache-max-size-none
    "W0410",  # misplaced-future
    "W1303",  # missing-format-argument-key
    "W0131",  # named-expr-without-context
    "W0177",  # nan-comparison
    "W3301",  # nested-min-max
    "W2402",  # non-ascii-file-name
    "W0133",  # pointless-exception-statement
    "W0104",  # pointless-statement
    "W0212",  # protected-access
    "W0707",  # raise-missing-from
    "W0622",  # redefined-builtin
    "W2901",  # redefined-loop-name
    "W1406",  # redundant-u-string-prefix
    "W0404",  # reimported
    "W0127",  # self-assigning-variable
    "W1509",  # subprocess-popen-preexec-fn
    "W1510",  # subprocess-run-check
    "W0245",  # super-without-brackets
    "W0706",  # try-except-raise
    "W0012",  # unknown-option-value
    "W2301",  # unnecessary-ellipsis
    "W0108",  # unnecessary-lambda
    "W0107",  # unnecessary-pass
    "W0301",  # unnecessary-semicolon
    "W1514",  # unspecified-encoding
    "W0613",  # unused-argument
    "W1304",  # unused-format-string-argument
    "W1301",  # unused-format-string-key
    "W0611",  # unused-import
    "W0612",  # unused-variable
    "W0120",  # useless-else-on-loop
    "W2101",  # useless-with-lock
    "W2601",  # using-f-string-in-unsupported-version
    "W0401",  # wildcard-import
    "C0202",  # bad-classmethod-argument
    "C0198",  # bad-docstring-quotes
    "C1901",  # compare-to-empty-string
    "C0201",  # consider-iterating-dictionary
    "C0501",  # consider-using-any-or-all
    "C0206",  # consider-using-dict-items
    "C0199",  # docstring-first-line-empty
    "C0112",  # empty-docstring
    "C0415",  # import-outside-toplevel
    "C2701",  # import-private-name
    "C0103",  # invalid-name
    "C0301",  # line-too-long
    "C2201",  # misplaced-comparison-constant
    "C0115",  # missing-class-docstring
    "C0304",  # missing-final-newline
    "C0116",  # missing-function-docstring
    "C0114",  # missing-module-docstring
    "C0410",  # multiple-imports
    "C0321",  # multiple-statements
    "C2403",  # non-ascii-module-import
    "C2401",  # non-ascii-name
    "C0205",  # single-string-used-for-slots
    "C0121",  # singleton-comparison
    "C0305",  # trailing-newlines
    "C0303",  # trailing-whitespace
    "C0131",  # typevar-double-variance
    "C0105",  # typevar-name-incorrect-variance
    "C0132",  # typevar-name-mismatch
    "C0412",  # ungrouped-imports
    "C0123",  # unidiomatic-typecheck
    "C3002",  # unnecessary-direct-lambda-call
    "C2801",  # unnecessary-dunder-call
    "C3001",  # unnecessary-lambda-assignment
    "C0113",  # unneeded-not
    "C1802",  # use-implicit-booleaness-not-len
    "C0208",  # use-sequence-for-iteration
    "C0414",  # useless-import-alias
    "C0411",  # wrong-import-order
    "C0413",  # wrong-import-position
    "R0133",  # comparison-of-constants
    "R0124",  # comparison-with-itself
    "R6003",  # consider-alternative-union-syntax
    "R1701",  # consider-merging-isinstance
    "R6002",  # consider-using-alias
    "R6104",  # consider-using-augmented-assign
    "R1717",  # consider-using-dict-comprehension
    "R0402",  # consider-using-from-import
    "R1728",  # consider-using-generator
    "R1715",  # consider-using-get
    "R1714",  # consider-using-in
    "R1730",  # consider-using-min-builtin
    "R1731",  # consider-using-max-builtin
    "R1718",  # consider-using-set-comprehension
    "R1722",  # consider-using-sys-exit
    "R1706",  # consider-using-ternary
    "R1732",  # consider-using-with
    "R5501",  # else-if-used
    "R2044",  # empty-comment
    "R1710",  # inconsistent-return-statements
    "R0123",  # literal-comparison
    "R2004",  # magic-value-comparison
    "R0202",  # no-classmethod-decorator
    "R1723",  # no-else-break
    "R1724",  # no-else-continue
    "R1720",  # no-else-raise
    "R1705",  # no-else-return
    "R6301",  # no-self-use
    "R0203",  # no-staticmethod-decorator
    "R0206",  # property-with-parameters
    "R1704",  # redefined-argument-from-local
    "R1719",  # simplifiable-if-expression
    "R1703",  # simplifiable-if-statement
    "R1725",  # super-with-arguments
    "R1260",  # too-complex
    "R0913",  # too-many-arguments
    "R0916",  # too-many-boolean-expressions
    "R0912",  # too-many-branches
    "R0914",  # too-many-locals
    "R1702",  # too-many-nested-blocks
    "R0904",  # too-many-public-methods
    "R0911",  # too-many-return-statements
    "R0915",  # too-many-statements
    "R1707",  # trailing-comma-tuple
    "R1721",  # unnecessary-comprehension
    "R1729",  # use-a-generator
    "R1733",  # unnecessary-dict-index-lookup
    "R1734",  # use-list-literal
    "R1735",  # use-dict-literal
    "R1734",  # use-list-literal
    "R6201",  # use-set-for-membership
    "R0205",  # useless-object-inheritance
    "R0022",  # useless-option-value
    "R1711",  # useless-return
]
