[nitpick.meta]
name = "taplo"
url = "https://github.com/tamasfe/taplo"

[nitpick.files.present]
".taplo.toml" = "Create the file with the contents below"



# https://taplo.tamasfe.dev/configuration/formatter-options.html
[".taplo.toml".formatting]
align_entries = false
align_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
inline_table_expand = true
compact_entries = false
column_width = 80
indent_tables = false
indent_entries = false
indent_string = '    '
trailing_newline = true
reorder_keys = false
reorder_arrays = false
reorder_inline_tables = false
allowed_blank_lines = 2
crlf = false
